In [2]:
import pandas as pd
import numpy as np

In [2]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [4]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

vector_vector_multiplication(u, v)

np.float64(14.0)

In [5]:
u.dot(v)

np.int64(14)

In [6]:
U = np.array([
[2, 4, 5, 6],
[1, 2, 1, 2],
[3, 1, 2, 1],
])
U.shape

(3, 4)

In [7]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [8]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [9]:
U.dot(v)

array([14,  5,  5])

In [6]:
print(pd.__version__)

3.0.5

In [7]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [8]:
df = pd.DataFrame(data, columns=columns)

In [9]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [10]:
df.info

<bound method DataFrame.info of       Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC
2    Lotus     Elise  2010      218.0                 4            MANUAL
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC
4   Nissan  Frontier  2017      261.0                 6            MANUAL

  Vehicle_Style   MSRP
0         sedan   2000
1         Sedan  27150
2   convertible  54990
3       4dr SUV  34450
4        Pickup  32340  >

In [11]:
len(df)

5

In [12]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000